// Add more sample plans for richer demo data
const samplePlans = [
  {
    _id: '1',
    nameoftheplace: 'Paris',
    abouttheplace: 'The city of lights, romance, and art.',
    adventuresactivitiestodo: [
      'Climb the Eiffel Tower',
      'Seine River Cruise',
      'Bike tour of the city',
      'Hot air balloon ride',
      'Explore Montmartre',
      'Visit Disneyland Paris',
      'Night walk at Champs-Élysées',
      'Picnic at Luxembourg Gardens',
    ],
    topplacestovisit: [
      'Eiffel Tower',
      'Louvre Museum',
      'Notre-Dame Cathedral',
      'Montmartre',
      'Sainte-Chapelle',
      'Luxembourg Gardens',
      'Champs-Élysées',
      'Palace of Versailles',
    ],
    itinerary: [
      'Day 1: Eiffel Tower, Seine River Cruise',
      'Day 2: Louvre Museum, Montmartre',
      'Day 3: Notre-Dame, Sainte-Chapelle',
      'Day 4: Versailles, Luxembourg Gardens',
      'Day 5: Disneyland Paris',
    ],
    localcuisinerecommendations: [
      'Croissants',
      'Baguette',
      'Escargot',
      'Crêpes',
      'Ratatouille',
      'French cheese',
      'Duck confit',
      'Macarons',
    ],
    packingchecklist: [
      'Passport',
      'Travel adapter',
      'Comfortable shoes',
      'Umbrella',
      'Camera',
      'Light jacket',
      'Guidebook',
      'Reusable water bottle',
    ],
    besttimetovisit: 'April to June and October to early November are the best times to visit Paris.',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
    isPublished: true,
    companion: 'friends',
    activityPreferences: ['sightseeing', 'food', 'adventure'],
    fromDate: 1680307200000,
    toDate: 1680739200000,
    userPrompt: 'A fun trip to Paris with friends.'
  },
  {
    _id: '2',
    nameoftheplace: 'Tokyo',
    abouttheplace: 'A vibrant city blending tradition and technology.',
    adventuresactivitiestodo: [
      'Visit Shibuya Crossing',
      'Sumo wrestling match',
      'Cherry blossom viewing',
      'Tsukiji Fish Market tour',
      'Anime shopping in Akihabara',
      'Day trip to Mt. Fuji',
      'Robot Restaurant show',
      'Explore Harajuku',
    ],
    topplacestovisit: [
      'Tokyo Tower',
      'Senso-ji Temple',
      'Meiji Shrine',
      'Ueno Park',
      'Akihabara',
      'Shinjuku Gyoen',
      'Tsukiji Market',
      'Odaiba',
    ],
    itinerary: [
      'Day 1: Senso-ji, Ueno Park',
      'Day 2: Meiji Shrine, Harajuku',
      'Day 3: Akihabara, Shibuya',
      'Day 4: Mt. Fuji day trip',
      'Day 5: Odaiba, Robot Restaurant',
    ],
    localcuisinerecommendations: [
      'Sushi',
      'Ramen',
      'Tempura',
      'Okonomiyaki',
      'Takoyaki',
      'Yakitori',
      'Mochi',
      'Matcha desserts',
    ],
    packingchecklist: [
      'Passport',
      'IC card (Suica/Pasmo)',
      'Comfortable shoes',
      'Umbrella',
      'Power adapter',
      'Camera',
      'Light jacket',
      'Cash (Yen)',
    ],
    besttimetovisit: 'March to May and October to November are ideal for Tokyo.',
    imageUrl: 'https://images.unsplash.com/photo-1464983953574-0892a716854b',
    isPublished: true,
    companion: 'solo',
    activityPreferences: ['culture', 'food', 'technology'],
    fromDate: 1680912000000,
    toDate: 1681344000000,
    userPrompt: 'Solo adventure in Tokyo.'
  },
  {
    _id: '3',
    nameoftheplace: 'New York',
    abouttheplace: 'The city that never sleeps, full of iconic sights.',
    adventuresactivitiestodo: [
      'Statue of Liberty ferry',
      'Broadway show',
      'Central Park bike ride',
      'Empire State Building visit',
      'Walk the Brooklyn Bridge',
      'Yankees baseball game',
      'Museum hopping',
      'Times Square at night',
    ],
    topplacestovisit: [
      'Statue of Liberty',
      'Central Park',
      'Empire State Building',
      'Metropolitan Museum of Art',
      'Brooklyn Bridge',
      'Times Square',
      'Grand Central Terminal',
      '9/11 Memorial',
    ],
    itinerary: [
      'Day 1: Statue of Liberty, Battery Park',
      'Day 2: Central Park, Museum Mile',
      'Day 3: Empire State, Times Square',
      'Day 4: Brooklyn Bridge, DUMBO',
      'Day 5: Broadway, Grand Central',
    ],
    localcuisinerecommendations: [
      'Bagels',
      'New York pizza',
      'Cheesecake',
      'Hot dogs',
      'Pastrami sandwich',
      'Dim sum in Chinatown',
      'Pretzels',
      'Cupcakes',
    ],
    packingchecklist: [
      'Passport/ID',
      'MetroCard',
      'Walking shoes',
      'Weather-appropriate clothes',
      'Camera',
      'Guidebook',
      'Reusable water bottle',
      'Umbrella',
    ],
    besttimetovisit: 'April to June and September to early November are best for NYC.',
    imageUrl: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
    isPublished: true,
    companion: 'family',
    activityPreferences: ['sightseeing', 'shows', 'food'],
    fromDate: 1681516800000,
    toDate: 1681948800000,
    userPrompt: 'Family trip to New York City.'
  },
  {
    _id: '4',
    nameoftheplace: 'Rome',
    abouttheplace: 'A city of ancient history, art, and delicious food.',
    adventuresactivitiestodo: [
      'Colosseum tour',
      'Vatican Museums',
      'Toss a coin in Trevi Fountain',
      'Gelato tasting',
      'Trastevere nightlife',
      'Roman Forum walk',
      'Cooking class',
      'Day trip to Pompeii',
    ],
    topplacestovisit: [
      'Colosseum',
      'Pantheon',
      'Trevi Fountain',
      'Vatican City',
      'Roman Forum',
      'Piazza Navona',
      'Spanish Steps',
      'Castel Sant’Angelo',
    ],
    itinerary: [
      'Day 1: Colosseum, Roman Forum',
      'Day 2: Vatican Museums, St. Peter’s',
      'Day 3: Pantheon, Trevi Fountain',
      'Day 4: Trastevere, Piazza Navona',
      'Day 5: Pompeii day trip',
    ],
    localcuisinerecommendations: [
      'Carbonara',
      'Cacio e pepe',
      'Gelato',
      'Roman pizza',
      'Supplì',
      'Tiramisu',
      'Espresso',
      'Saltimbocca',
    ],
    packingchecklist: [
      'Passport',
      'Travel adapter',
      'Walking shoes',
      'Sunscreen',
      'Camera',
      'Guidebook',
      'Reusable water bottle',
      'Hat',
    ],
    besttimetovisit: 'April to June and late September to October are best for Rome.',
    imageUrl: 'https://images.unsplash.com/photo-1509395176047-4a66953fd231',
    isPublished: true,
    companion: 'couple',
    activityPreferences: ['history', 'food', 'art'],
    fromDate: 1682121600000,
    toDate: 1682553600000,
    userPrompt: 'Romantic getaway to Rome.'
  },
  {
    _id: '5',
    nameoftheplace: 'Sydney',
    abouttheplace: 'A sunny city with iconic beaches and landmarks.',
    adventuresactivitiestodo: [
      'Sydney Opera House tour',
      'Climb Sydney Harbour Bridge',
      'Surf at Bondi Beach',
      'Ferry to Manly',
      'Taronga Zoo visit',
      'Blue Mountains day trip',
      'Kayak in Sydney Harbour',
      'Coastal walk from Bondi to Coogee',
    ],
    topplacestovisit: [
      'Sydney Opera House',
      'Harbour Bridge',
      'Bondi Beach',
      'Darling Harbour',
      'The Rocks',
      'Taronga Zoo',
      'Manly Beach',
      'Blue Mountains',
    ],
    itinerary: [
      'Day 1: Opera House, The Rocks',
      'Day 2: Bondi Beach, Coastal Walk',
      'Day 3: Taronga Zoo, Manly',
      'Day 4: Blue Mountains',
      'Day 5: Harbour Bridge climb',
    ],
    localcuisinerecommendations: [
      'Meat pie',
      'Barramundi',
      'Lamingtons',
      'Pavlova',
      'Fish and chips',
      'Vegemite toast',
      'Flat white coffee',
      'Tim Tams',
    ],
    packingchecklist: [
      'Passport',
      'Sunscreen',
      'Swimwear',
      'Hat',
      'Sunglasses',
      'Camera',
      'Reusable water bottle',
      'Walking shoes',
    ],
    besttimetovisit: 'September to November and March to May are best for Sydney.',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
    isPublished: true,
    companion: 'friends',
    activityPreferences: ['beach', 'adventure', 'sightseeing'],
    fromDate: 1682726400000,
    toDate: 1683158400000,
    userPrompt: 'Beach adventure in Sydney.'
  },
  {
    _id: '6',
    nameoftheplace: 'Cape Town',
    abouttheplace: 'A city of mountains, beaches, and vibrant culture.',
    adventuresactivitiestodo: [
      'Table Mountain hike',
      'Robben Island tour',
      'Cape Point drive',
      'Boulders Beach penguins',
      'Winelands tour',
      'V&A Waterfront shopping',
      'Surfing at Muizenberg',
      'Kirstenbosch Gardens',
    ],
    topplacestovisit: [
      'Table Mountain',
      'Robben Island',
      'Cape Point',
      'Boulders Beach',
      'V&A Waterfront',
      'Kirstenbosch Gardens',
      'Muizenberg Beach',
      'Stellenbosch Winelands',
    ],
    itinerary: [
      'Day 1: Table Mountain, V&A Waterfront',
      'Day 2: Robben Island, Boulders Beach',
      'Day 3: Cape Point, Winelands',
      'Day 4: Kirstenbosch, Muizenberg',
      'Day 5: Free day for shopping',
    ],
    localcuisinerecommendations: [
      'Biltong',
      'Bobotie',
      'Cape Malay curry',
      'Braai',
      'Koeksisters',
      'Snoek',
      'Malva pudding',
      'Rooibos tea',
    ],
    packingchecklist: [
      'Passport',
      'Sunscreen',
      'Hat',
      'Camera',
      'Guidebook',
      'Reusable water bottle',
      'Walking shoes',
      'Swimwear',
    ],
    besttimetovisit: 'March to May and September to November are best for Cape Town.',
    imageUrl: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
    isPublished: true,
    companion: 'family',
    activityPreferences: ['nature', 'food', 'adventure'],
    fromDate: 1683331200000,
    toDate: 1683763200000,
    userPrompt: 'Family trip to Cape Town.'
  },
  {
    _id: '7',
    nameoftheplace: 'Istanbul',
    abouttheplace: 'A city where East meets West, rich in history and culture.',
    adventuresactivitiestodo: [
      'Hagia Sophia visit',
      'Grand Bazaar shopping',
      'Bosphorus cruise',
      'Blue Mosque tour',
      'Turkish bath experience',
      'Spice Market',
      'Topkapi Palace',
      'Street food tour',
    ],
    topplacestovisit: [
      'Hagia Sophia',
      'Blue Mosque',
      'Grand Bazaar',
      'Topkapi Palace',
      'Bosphorus',
      'Spice Market',
      'Galata Tower',
      'Basilica Cistern',
    ],
    itinerary: [
      'Day 1: Hagia Sophia, Blue Mosque',
      'Day 2: Topkapi Palace, Basilica Cistern',
      'Day 3: Grand Bazaar, Spice Market',
      'Day 4: Bosphorus cruise, Galata Tower',
      'Day 5: Turkish bath, street food',
    ],
    localcuisinerecommendations: [
      'Kebabs',
      'Baklava',
      'Meze',
      'Simit',
      'Turkish delight',
      'Lahmacun',
      'Menemen',
      'Turkish tea',
    ],
    packingchecklist: [
      'Passport',
      'Headscarf (for mosques)',
      'Comfortable shoes',
      'Camera',
      'Guidebook',
      'Reusable water bottle',
      'Sunscreen',
      'Umbrella',
    ],
    besttimetovisit: 'April to May and September to November are best for Istanbul.',
    imageUrl: 'https://images.unsplash.com/photo-1509395176047-4a66953fd231',
    isPublished: true,
    companion: 'couple',
    activityPreferences: ['history', 'food', 'shopping'],
    fromDate: 1683936000000,
    toDate: 1684368000000,
    userPrompt: 'Cultural exploration in Istanbul.'
  }
];

export default samplePlans;
